name: Secure Integration test

on:
  pull_request_target:
    types: [opened, synchronize, labeled, unlabled, reopened]

jobs:
  check-access-and-checkout:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: read
      contents: read
    steps:
      - name: Check PR labels and author
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            const labels = pr.labels.map(label => label.name);
            const hasLabel = labels.includes('approved-for-integ-test')
            if (hasLabel) {
              core.info('PR contains label approved-for-integ-test')
              return
            }
            
            const isOwner = pr.user.type === 'User' && pr.user.login === context.repo.owner;
            if (isOwner) {
              core.info('PR auther is an OWNER')
              return
            }

            core.setFailed('Pull Request must either have label approved-for-integ-test or be created by an owner')

      - name: Configure Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with: 
         role-to-assume: ${{ secrets.STRANDS_INTEG_TEST_ROLE }}
         aws-region: us-east-1
      - name: Set LLM Provider Env Vars
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            LLAMA_API_KEY, ${{ secrets.STRANDS_LLAMAAPI_API_KEY_SECRET }}
            OPENAI_API_KEY, ${{ secrets.STRANDS_OPENAI_API_KEY_SECRET }}
            ANTHROPIC_API_KEY, ${{ secrets.STRANDS_ANTHROPIC_API_KEY_SECRET }}
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      
    
