name: Secure Integration test

on:
  pull_request_target:
    branches: main
  push:
    branches: mcp/windows

jobs:
  check-access-and-checkout:
    runs-on: "windows-latest"
    permissions:
      id-token: write
      pull-requests: read
      contents: read
    steps:
      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         role-to-assume: ${{ secrets.STRANDS_INTEG_TEST_ROLE }}
         aws-region: us-east-1
         mask-aws-account-id: true
      - name: Checkout head commit
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Pull the commit from the forked repo
          persist-credentials: false  # Don't persist credentials for subsequent actions
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --no-cache-dir hatch
      - name: Run integration tests
        env:
          AWS_REGION: us-east-1
          AWS_REGION_NAME: us-east-1 # Needed for LiteLLM
          STRANDS_TEST_API_KEYS_SECRET_NAME: ${{ secrets.STRANDS_TEST_API_KEYS_SECRET_NAME }}
        id: tests
        run: |
          hatch test tests_integ/test_mcp_client.py
