name: Secure Integration test

on:
  pull_request_target:
    types: [opened, synchronize, labeled, unlabled, reopened]
  push:
    branches:
      - dea/integ-test
jobs:
  check-access-and-checkout:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: read
      contents: read
    steps:
      - name: Check PR labels and author
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            if (!(hasLabel || isOwner)) {
      - name: Configure Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with: 
         role-to-assume: ${{ secrets.STRANDS_INTEG_TEST_ROLE }}
         aws-region: us-east-1
      - name: Set LLM Provider Env VarsMore actions
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            LLAMA_API_KEY, ${{ secrets.STRANDS_LLAMAAPI_API_KEY_SECRET }}
            OPENAI_API_KEY, ${{ secrets.STRANDS_OPENAI_API_KEY_SECRET }}
            ANTHROPIC_API_KEY, ${{ secrets.STRANDS_ANTHROPIC_API_KEY_SECRET }}
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      
    
