name: Test and Lint

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  unit-test:
    name: Unit Tests - Python ${{ matrix.python-version }} - ${{ matrix.os-name }}
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
       include:
        - os: ubuntu-latest
          os-name: 'linux'
          python-version: "3.13"
        # Windows
        - os: windows-latest
          os-name: 'windows'
          python-version: "3.13"
        # MacOS - latest only; not enough runners for macOS
        - os: macos-latest
          os-name: 'macOS'
          python-version: "3.13"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      LOG_LEVEL: DEBUG
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}  # Explicitly define which commit to check out
          persist-credentials: false  # Don't persist credentials for subsequent actions
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --no-cache-dir hatch
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run MCP Integ
        run: hatch run test-integ-mcp
