name: Verify Tools Compatibility
 
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
 
jobs:
  test-dependency:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
 
    steps:
      - name: Checkout sdk-python
        uses: actions/checkout@v4
        with:
          path: sdk-python
      - name: Checkout Tools Repository
        uses: actions/checkout@v4
        with:
          repository: strands-agents/tools
          path: tools
      - name: Checkout Agent Builder Repository
        uses: actions/checkout@v4
        with:
          repository: strands-agents/agent-builder
          path: agent-builder
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --no-cache-dir hatch
      - name: Patch tools dependency on sdk-python and test
        run: |
          cd tools
          
          sed -i "s|.*strands-agents>.*|\"strands-agents @ file://${GITHUB_WORKSPACE}/sdk-python/\",|" pyproject.toml
         
          count=$(grep -c "strands-agents @ file://${GITHUB_WORKSPACE}/sdk-python" pyproject.toml)
          if [ "$count" -eq 2 ]; then
            echo "Dependency found exactly twice in pyproject.toml"
          else
            echo "Dependency found $count times, expected 2"
            exit 1
          fi
          
          hatch run test
